name: CI
on:
  push:
    branches:
    - main
jobs:
  run_unittests:
    name: hz
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v4

    - name: echo
      run: echo HELLO!!
    
    - name: run install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    
  
