name: CI
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: poetry install --no-interaction
      - name: postgres
        uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: postgres
          password: postgres
          database: postgres
          port: 5432
      - name: Make migration
        run: poetry run python devops_demo/manage.py makemigrations
      - name: Migrate
        run: poetry run python devops_demo/manage.py migrate
      - name: Tests
        run: cd devops_demo && poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4  
#      - name: 
  
